# Site base metadata
site_name: python-multibar
site_description: "Flexible wrapper for static progressbar writing."
site_dir: "site"

docs_dir: docs/

# Github metadata
repo_url: https://github.com/Animatea/python-multibar
repo_name: Animatea/python-multibar
edit_uri: https://github.com/Animatea/python-multibar/tree/main/docs

# Theme configuration
theme:
  name: material
  logo: assets/docs-logo.png

  icon:
    edit: material/file-document-edit-outline

  favicon: assets/docs-icon.png
  custom_dir: overrides

  palette:
    - scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

# Navigation menu
nav:
  - "Home":
    - index.md

  - Quickstart:
    - quickstart.md

  - FAQ:
    - faq.md

  - About:
    - about.md

  - Showcase:
    - showcase.md

  - "Reference":
      - "api":
        - api/math_operations.md
        - api/clients.md
        - api/contracts.md
        - api/hooks.md
        - api/progressbars.md
        - api/sectors.md
        - api/signatures.md
        - api/writers.md

      - "impl":
        - impl/math_operations.md
        - impl/clients.md
        - impl/contracts.md
        - impl/hooks.md
        - impl/progressbars.md
        - impl/sectors.md
        - impl/signatures.md
        - impl/writers.md

      - Errors: errors.md
      - Console: output.md
      - Settings: settings.md
      - Types: types.md
      - Utilities: utilities.md

plugins:
  - search
  - autorefs
  - termynal

  # Plugin for diagrams
  - mermaid2:
      arguments:
        theme: "dark"

  # Code auto reference plugin
  - mkdocstrings:
      default_handler: python

      handlers:
        python:

          selection:
            docstring_style: numpy  # <--- In our project we use `numpy` docstring style.
            inherited_members: true

          rendering:
            docstring_section_style: spacy
            show_if_no_docstring: true
            merge_init_into_class: false
            show_signature_annotations: false
            show_source: true
            show_submodules: false
            show_root_heading: true
            separate_signature: false

          import:
            # For argument types "footnotes".
            - https://returns.readthedocs.io/en/latest/objects.inv
            - https://docs.python.org/3.9/objects.inv

      watch:
        # Observe for updates
        - multibar


# Documentation Extensions
markdown_extensions:
  - markdown.extensions.attr_list
  - pymdownx.progressbar
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.details

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - tables

  - toc:
      permalink: "¤"

# Additional css
extra_css:
  - css/material.css
  - css/mkdocs.css
  - css/progressbar.css
  - css/critic.css
  - css/navmenu.css
  - css/emojis.css

# Additional javascript
extra_javascript:
  - js/mermaid.js
  - js/tabs.js

# Extra metadata
extra:
  # Footer icons
  social:
    - icon: fontawesome/brands/python  # Pypi
      link: https://pypi.org/project/python-multibar/

    - icon: fontawesome/brands/discord  # Discord server
      link: discord.gg/KKUFRZCt4f

copyright: >
  Copyright &copy; 2022 DenyS
